name: Material Segmented Control
description: A material segmented control like the one for iOS, but in Material design
version: 0.1.1
author: The.BENN<benjaminkraatz@yahoo.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
